

services:
  db:
    image: postgres:15-alpine
    container_name: area_postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - area_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U area -d area_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: area_server
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - area_network
    volumes:
      - ./server/src:/app/src

  web:
    build:
      context: ./front-web
      dockerfile: Dockerfile
    container_name: area_web
    ports:
      - "8081:80"
    depends_on:
      - server
    networks:
      - area_network
    volumes:
      - ./client-mobile/output:/usr/share/nginx/html/downloads

  mobile_builder:
    build:
      context: ./client-mobile
      dockerfile: Dockerfile
    container_name: area_mobile_builder
    volumes:
      - ./client-mobile/output:/output
    networks:
      - area_network
    command: sh -c "./gradlew assembleDebug && cp app/build/outputs/apk/debug/app-debug.apk /output/aea-mobile.apk"

volumes:
  postgres_data:

networks:
  area_network:
    driver: bridge
